# Generated by Django 3.2 on 2022-10-09 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import inventory.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Csvs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.FileField(upload_to="csvs")),
                ("upload_date", models.DateTimeField(auto_now=True)),
                ("activated", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("Make", models.CharField(max_length=50)),
                ("Part_Code", models.CharField(max_length=100)),
                ("Serial_Number", models.TextField(primary_key=True, serialize=False)),
                ("Item", models.CharField(max_length=50)),
                ("Location", models.TextField()),
                (
                    "Purchase_Date",
                    models.DateField(default=datetime.datetime.now, null=True),
                ),
                ("Item_dispatched_Date", models.DateField(null=True)),
                (
                    "Status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("None", "None"),
                            ("Working", "Working"),
                            ("Not Working", "Not Working"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "Slip",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        validators=[inventory.validators.validate_file_extension],
                    ),
                ),
                (
                    "Organisation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="customer.organisation",
                    ),
                ),
            ],
            options={
                "db_table": "Inventory",
            },
        ),
    ]
