# Generated by Django 3.2 on 2022-10-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='Slip',
            new_name='CLI_snapshot',
        ),
    ]
