# Generated by Django 3.2 on 2022-10-12 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_alter_inventory_snapshot_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="Item_dispatched_Date",
            field=models.DateField(
                null=True, verbose_name="Item Dispatch Date (mm/dd/yyyy)"
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="Purchase_Date",
            field=models.DateField(
                default=datetime.datetime.now,
                null=True,
                verbose_name="Purchase Date (mm/dd/yyyy)",
            ),
        ),
    ]
