# Generated by Django 3.2 on 2022-10-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20221012_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Status',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Working', 'Working'), ('Not Working', 'Not Working')], max_length=20),
        ),
    ]
