# Generated by Django 3.2 on 2022-09-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_auto_20220707_0924"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="Status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("None", "None"),
                    ("Working", "Working"),
                    ("Not Working", "Not Working"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
