# Generated by Django 3.2 on 2022-10-09 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('TicketID', models.AutoField(primary_key=True, serialize=False, verbose_name='Ticket ID')),
                ('DateCreated', models.DateField(default=django.utils.timezone.now, verbose_name='Date Created (mm/dd/yyyy)')),
                ('Category', models.CharField(max_length=100)),
                ('SubCategory', models.CharField(max_length=100, verbose_name='Sub-Category')),
                ('Summary', models.TextField(blank=True, max_length=500)),
                ('Priority', models.CharField(blank=True, choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], max_length=2)),
                ('Status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('Pending', 'Pending'), ('Closed', 'Closed')], max_length=10)),
                ('FaultFoundCode', models.CharField(blank=True, choices=[('---------', '---------'), ('Router', 'Router faulty'), ('Modem', 'Modem faulty'), ('Switch', 'Switch faulty')], max_length=30, verbose_name='Fault Found Code')),
                ('ResolutionCode', models.CharField(blank=True, choices=[('---------', '---------'), ('123', 'Router faulty'), ('456', 'Modem faulty')], max_length=20, verbose_name='Resolution Code')),
                ('ResolutionRemarks', models.TextField(blank=True, max_length=500, verbose_name='Resolution Remarks')),
                ('OnlineResolvable', models.CharField(blank=True, choices=[('---------', '---------'), ('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Online Resolvable')),
                ('ResolutionDate', models.DateField(blank=True, null=True, verbose_name='Resolution Date (mm/dd/yyyy)')),
                ('DocketNumber', models.CharField(blank=True, max_length=50, verbose_name='Docket Number')),
                ('DispatchedThrough', models.CharField(blank=True, choices=[('---------', '---------'), ('Delhivery', 'Delhivery'), ('Blue Dart', 'Blue Dart')], max_length=50, verbose_name='Dispatched through')),
                ('DeliveryStatus', models.CharField(blank=True, choices=[('---------', '---------'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], max_length=30, verbose_name='Delivery Status')),
                ('AlternateHW', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replacement', to='inventory.inventory')),
                ('Customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer')),
                ('SerialNo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.inventory')),
            ],
            options={
                'db_table': 'Ticket',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTicket',
            fields=[
                ('TicketID', models.IntegerField(blank=True, db_index=True, verbose_name='Ticket ID')),
                ('DateCreated', models.DateField(default=django.utils.timezone.now, verbose_name='Date Created (mm/dd/yyyy)')),
                ('Category', models.CharField(max_length=100)),
                ('SubCategory', models.CharField(max_length=100, verbose_name='Sub-Category')),
                ('Summary', models.TextField(blank=True, max_length=500)),
                ('Priority', models.CharField(blank=True, choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], max_length=2)),
                ('Status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('Pending', 'Pending'), ('Closed', 'Closed')], max_length=10)),
                ('FaultFoundCode', models.CharField(blank=True, choices=[('---------', '---------'), ('Router', 'Router faulty'), ('Modem', 'Modem faulty'), ('Switch', 'Switch faulty')], max_length=30, verbose_name='Fault Found Code')),
                ('ResolutionCode', models.CharField(blank=True, choices=[('---------', '---------'), ('123', 'Router faulty'), ('456', 'Modem faulty')], max_length=20, verbose_name='Resolution Code')),
                ('ResolutionRemarks', models.TextField(blank=True, max_length=500, verbose_name='Resolution Remarks')),
                ('OnlineResolvable', models.CharField(blank=True, choices=[('---------', '---------'), ('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Online Resolvable')),
                ('ResolutionDate', models.DateField(blank=True, null=True, verbose_name='Resolution Date (mm/dd/yyyy)')),
                ('DocketNumber', models.CharField(blank=True, max_length=50, verbose_name='Docket Number')),
                ('DispatchedThrough', models.CharField(blank=True, choices=[('---------', '---------'), ('Delhivery', 'Delhivery'), ('Blue Dart', 'Blue Dart')], max_length=50, verbose_name='Dispatched through')),
                ('DeliveryStatus', models.CharField(blank=True, choices=[('---------', '---------'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], max_length=30, verbose_name='Delivery Status')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('AlternateHW', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventory')),
                ('Customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer.customer')),
                ('SerialNo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ticket',
                'verbose_name_plural': 'historical tickets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
