# Generated by Django 3.2 on 2022-10-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalticket",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical ticket",
            },
        ),
        migrations.AlterField(
            model_name="historicalticket",
            name="history_date",
            field=models.DateTimeField(),
        ),
    ]
