# Generated by Django 3.2 on 2022-09-23 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalticket",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical ticket",
            },
        ),
        migrations.AlterField(
            model_name="historicalticket",
            name="SerialNo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.inventory",
            ),
        ),
        migrations.AlterField(
            model_name="historicalticket",
            name="history_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="AlternateHW",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="replacement",
                to="inventory.inventory",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="SerialNo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="inventory.inventory"
            ),
        ),
    ]
