# Generated by Django 3.2 on 2022-10-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_auto_20221010_0008"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalticket",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical ticket",
                "verbose_name_plural": "historical tickets",
            },
        ),
        migrations.AlterField(
            model_name="historicalticket",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
