# Generated by Django 3.2 on 2022-10-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_auto_20221010_0607"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalticket",
            name="FaultFoundCode",
            field=models.CharField(max_length=30, verbose_name="Fault Found Code"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="FaultFoundCode",
            field=models.CharField(max_length=30, verbose_name="Fault Found Code"),
        ),
    ]
