# Generated by Django 3.2 on 2022-10-12 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0003_auto_20221011_0755"),
        ("crm", "0004_auto_20221012_1257"),
    ]

    operations = []
