# Generated by Django 3.2 on 2023-02-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0009_auto_20230221_1414"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalticket",
            name="Priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("P1", "P1"),
                    ("P2", "P2"),
                    ("P3", "P3"),
                    ("P4", "P4"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="Priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("P1", "P1"),
                    ("P2", "P2"),
                    ("P3", "P3"),
                    ("P4", "P4"),
                ],
                max_length=2,
            ),
        ),
    ]
