# Generated by Django 3.2 on 2022-09-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0012_auto_20220903_0704"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalticket",
            name="DateClosed",
            field=models.DateField(
                blank=True,
                default="",
                null=True,
                verbose_name="Date Closed (mm/dd/yyyy)",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="DateClosed",
            field=models.DateField(
                blank=True,
                default="",
                null=True,
                verbose_name="Date Closed (mm/dd/yyyy)",
            ),
        ),
    ]
