# Generated by Django 3.2 on 2022-09-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0013_auto_20220903_0705"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalticket",
            name="DateClosed",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date Closed (mm/dd/yyyy)"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="DateClosed",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date Closed (mm/dd/yyyy)"
            ),
        ),
    ]
