# Generated by Django 3.2 on 2022-09-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0014_auto_20220903_0824"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalticket",
            name="ModelNo",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="ModelNo",
        ),
        migrations.AlterField(
            model_name="historicalticket",
            name="DateClosed",
            field=models.DateField(blank=True, null=True, verbose_name="Date Closed"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="DateClosed",
            field=models.DateField(blank=True, null=True, verbose_name="Date Closed"),
        ),
    ]
